name: encceja_plus
description: Aplicativo gamificado para estudos do ENCCEJA
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.7
  
  # Navigation
  go_router: ^12.1.3
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # UI & Animations
  lottie: ^2.7.0
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  
  # PDF Support
  flutter_pdfview: ^1.3.2
  pdf: ^3.10.7
  url_launcher: ^6.2.2
  
  # Google Sign In
  google_sign_in: ^6.2.2
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Testing
  bloc_test: ^9.1.5
  mockito: ^5.4.4
  build_runner: ^2.4.7
  
  # Code Generation
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/sounds/
    - assets/library/
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
